CREATE TABLE CRWD_DNSTY.[REF].CALENDAR (
	CAL_D date NOT NULL,
	DAY_TP varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PH_F varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	TERM_F varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LOADG_DTM smalldatetime NULL,
	CONSTRAINT UQ__CALANDER__7DA275D10B59CD2F UNIQUE (CAL_D,DAY_TP,PH_F,TERM_F,LOADG_DTM)
);